#!/bin/bash

ask_for_sudo() {
	sudo -v

	while true; do
		sudo -n true
		sleep 60
		kill -0 "$$" || exit
	done &> /dev/null &
}

install_homebrew() {
	if [[ ! "$(type -P brew)" ]]; then
		echo ' ✔ install homebrew'
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
		echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> "$HOME/.bash_profile"
		eval "$(/opt/homebrew/bin/brew shellenv)"
	else
		echo ' # skip homebrew (already installed)'
	fi
	[[ ! "$(type -P brew)" ]] && echo " # Homebrew installation failed" && exit 1
}

install_znap() {
	if [[ ! -f ~/zsh/znap/znap.zsh ]]; then
		echo ' ✔ install znap for zsh'
		git clone --depth 1 https://github.com/marlonrichert/zsh-snap.git ~/zsh/znap
	else
		echo ' # skip znap (already installed)'
	fi
}

install_minpac() {
	if [[ ! -d ~/.vim/pack/minpac/opt/minpac ]]; then
		echo ' ✔ install minpac for vim'
		git clone --depth 1 https://github.com/k-takata/minpac.git ~/.vim/pack/minpac/opt/minpac
	else
		echo ' # skip minpac (already installed)'
	fi
}

main() {
	# install dotfiles

	echo '--- darthsoup dotfiles ---'
	echo '--- install ---'

	# ask for Sudo

	ask_for_sudo;

	# quick copy pasta to home

	echo " ✔ Copy: Copying dotfiles to home..."
	rsync -r \
		--exclude '.git' \
		--exclude '.editorconfig' \
		--exclude 'LICENSE.md' \
		--exclude 'README.md' \
		--exclude 'install' ./ $HOME

	install_homebrew
	install_znap
	install_minpac

	echo ' ✔ installation complete'
	echo ' # restart the shell'
}

main "$@"
